# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIaWB-PM7rTZrVkSBmhkw1E-Faed6akM
"""

import streamlit as st
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer 

# Scikit-learn (Modelos de Clasificación)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
# from sklearn.neighbors import KNeighborsClassifier  <-- ELIMINADO
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    auc,
)


# -----------------------------------------------------------
# FUNCIÓN PARA CARGAR CSV Y DETECTAR DELIMITADOR AUTOMÁTICO
# -----------------------------------------------------------
def cargar_csv(uploaded_file):
    contenido = uploaded_file.read().decode('latin-1', errors='ignore')
    uploaded_file.seek(0)

    try:
        dialect = csv.Sniffer().sniff(contenido.splitlines()[0])
        sep = dialect.delimiter
    except:
        sep = ','  # Si no detecta, usamos coma por defecto

    df = pd.read_csv(uploaded_file, sep=sep, engine="python")
    df.columns = df.columns.str.strip()

    # Intentar convertir columnas a numéricas, manteniendo categóricas como strings si fallan
    for col in df.columns:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.strip()
        )
        # Intentar convertir a numérico, si falla, queda como string (categórica)
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(df[col])

    return df


# -----------------------------------------------------------
# MÉTRICAS DE CLASIFICACIÓN
# -----------------------------------------------------------
def calculate_metrics_clf(y_true, y_pred, subset_name):
    return {
        'Conjunto': subset_name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Reporte_Clasificacion': classification_report(y_true, y_pred, output_dict=True, zero_division=0),
        'Matriz_Confusion': confusion_matrix(y_true, y_pred),
    }


# -----------------------------------------------------------
# INTERFAZ STREAMLIT
# -----------------------------------------------------------

st.set_page_config(page_title="Aplicación Interactiva de Modelos de Clasificación ML", layout="wide")

st.title("🤖 Aplicación Interactiva de Modelos de Clasificación")
st.markdown("---")

with st.sidebar:
    st.header("1. Cargar Datos CSV")
    uploaded_file = st.file_uploader("Seleccione archivo CSV", type=['csv'])

df = None
if uploaded_file:
    df = cargar_csv(uploaded_file)

    if df.shape[0] == 0:
        st.error("⚠ El archivo se cargó pero **no contiene filas válidas**. Revisa el delimitador o el formato.")
        st.stop()
    else:
        st.success(f"✅ Archivo cargado correctamente: {df.shape[0]} filas, {df.shape[1]} columnas.")
        st.dataframe(df.head())


if df is None:
    st.info("Por favor cargue un archivo CSV para continuar.")
    st.stop()


# Selección de variables
with st.sidebar:
    st.header("2. Selección de Variables")
    column_names = df.columns.tolist()

    selected_features = st.multiselect("Variables Independientes (X):", column_names, default=column_names[:-1])
    selected_target = st.selectbox("Variable Dependiente (Y - Categórica):", column_names, index=len(column_names)-1)

if selected_target in selected_features:
    st.error("❌ La variable Y no puede estar incluida en X.")
    st.stop()

# -------------------------------------------------
# PREPROCESAMIENTO ESPECÍFICO PARA CLASIFICACIÓN
# -------------------------------------------------

# 1. Transformación de X: One-Hot Encoding para variables categóricas seleccionadas
X_data = df[selected_features].copy()
X_processed = pd.get_dummies(X_data, drop_first=True) 
X = X_processed.values

# MANEJO DE VALORES FALTANTES (NaN) EN X
# Aunque se quitó KNN, la imputación es una buena práctica general.
if np.isnan(X).any():
    st.sidebar.warning("⚠️ Detectados y rellenados valores NaN en las características (X) usando la media.")
    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    X = imputer.fit_transform(X)


# 2. Transformación de Y: Label Encoding para la variable objetivo (debe ser numérica)
try:
    le = LabelEncoder()
    y = le.fit_transform(df[selected_target].astype(str).fillna('Missing'))
    class_names = le.classes_
    st.sidebar.success(f"Y Categórica codificada: {selected_target} -> {len(class_names)} Clases.")
except Exception as e:
    st.error(f"❌ Error al codificar la variable objetivo (Y): {e}")
    st.stop()


if X.shape[0] < 5:
    st.error("⚠ Se requieren al menos 5 observaciones para entrenar un modelo.")
    st.stop()

# División en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Selección del modelo
with st.sidebar:
    st.header("3. Modelo de Clasificación")
    models = {
        "Regresión Logística": LogisticRegression,
        "Árbol de Decisión": DecisionTreeClassifier,
        "Random Forest": RandomForestClassifier,
        # "K-Vecinos Cercanos (KNN)": KNeighborsClassifier, <-- ELIMINADO del menú
        "Máquinas de Soporte Vectorial (SVC)": SVC,
    }

    model_name = st.selectbox("Modelo:", list(models.keys()))

    # Parámetros específicos para Random Forest
    if model_name == "Random Forest":
        n_estimators = st.slider("N° de árboles:", 10, 300, 100)
        max_depth = st.slider("Profundidad máxima:", 2, 30, 10)
    
    # Parámetros específicos para SVC
    if model_name == "Máquinas de Soporte Vectorial (SVC)":
        kernel = st.selectbox("Kernel:", ['rbf', 'linear', 'poly', 'sigmoid'])
        C = st.slider("Parámetro C:", 0.1, 10.0, 1.0)
    
    # Se eliminaron los parámetros específicos para KNN aquí


if st.sidebar.button("✅ Entrenar Modelo"):
    model_class = models[model_name]

    # Inicialización del modelo
    if model_name == "Random Forest":
        model = model_class(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    elif model_name == "Máquinas de Soporte Vectorial (SVC)":
        # Nota: SVC por defecto no tiene predict_proba, lo que afectará la Curva ROC si no se añade probability=True, pero lo dejamos simple.
        model = model_class(kernel=kernel, C=C, random_state=42)
    elif model_name == "Regresión Logística":
         model = model_class(max_iter=500, random_state=42)
    else:
        # Aquí también se incluye DecisionTree y cualquier otro modelo simple
        model = model_class(random_state=42)
    
    # Entrenamiento
    model.fit(X_train, y_train)

    # Predicciones
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Cálculo de Métricas
    metrics_train = calculate_metrics_clf(y_train, y_train_pred, "Entrenamiento")
    metrics_test = calculate_metrics_clf(y_test, y_test_pred, "Validación")

    st.header("📊 Resultados del Modelo de Clasificación")

    # Presentación de Accuracy
    st.markdown("### 🎯 Precisión (Accuracy)")
    accuracy_df = pd.DataFrame({
        'Conjunto': ["Entrenamiento", "Validación"],
        'Accuracy': [metrics_train['Accuracy'], metrics_test['Accuracy']]
    }).set_index('Conjunto')
    st.table(accuracy_df.style.format({'Accuracy': '{:.4f}'}))

    # Presentación de Reporte de Clasificación (Entrenamiento y Validación)
    st.markdown("### 📋 Reporte de Clasificación")
    col_rep1, col_rep2 = st.columns(2)
    
    with col_rep1:
        st.subheader("Entrenamiento")
        report_df_train = pd.DataFrame(metrics_train['Reporte_Clasificacion']).transpose()
        st.dataframe(report_df_train.drop(columns=['support']).style.format('{:.2f}'))

    with col_rep2:
        st.subheader("Validación")
        report_df_test = pd.DataFrame(metrics_test['Reporte_Clasificacion']).transpose()
        st.dataframe(report_df_test.drop(columns=['support']).style.format('{:.2f}'))
    
    # ---------------------------------------------
    # Gráficos: Matriz de Confusión
    # ---------------------------------------------
    st.header("📈 Matriz de Confusión")
    st.markdown("> La Matriz de Confusión muestra cuántas predicciones fueron correctas (diagonal principal) y cuántas incorrectas.")
    
    col_cm1, col_cm2 = st.columns(2)

    # Matriz de Confusión (Entrenamiento)
    with col_cm1:
        st.subheader("Entrenamiento")
        cm_train = metrics_train['Matriz_Confusion']
        fig_cm_train, ax_cm_train = plt.subplots(figsize=(6, 6))
        sns.heatmap(cm_train, annot=True, fmt='d', cmap='Blues', cbar=False,
                    xticklabels=class_names, yticklabels=class_names, ax=ax_cm_train)
        ax_cm_train.set_ylabel('Valor Real')
        ax_cm_train.set_xlabel('Valor Predicho')
        ax_cm_train.set_title("Matriz de Confusión - Entrenamiento")
        st.pyplot(fig_cm_train)

    # Matriz de Confusión (Validación)
    with col_cm2:
        st.subheader("Validación")
        cm_test = metrics_test['Matriz_Confusion']
        fig_cm_test, ax_cm_test = plt.subplots(figsize=(6, 6))
        sns.heatmap(cm_test, annot=True, fmt='d', cmap='Greens', cbar=False,
                    xticklabels=class_names, yticklabels=class_names, ax=ax_cm_test)
        ax_cm_test.set_ylabel('Valor Real')
        ax_cm_test.set_xlabel('Valor Predicho')
        ax_cm_test.set_title("Matriz de Confusión - Validación")
        st.pyplot(fig_cm_test)
        
    # Opcional: Curva ROC (solo para clasificación binaria y modelos con predict_proba)
    if len(class_names) == 2 and hasattr(model, "predict_proba"):
        st.header("📉 Curva ROC (Clasificación Binaria)")
        
        # Predicciones de probabilidad
        y_score_train = model.predict_proba(X_train)[:, 1]
        y_score_test = model.predict_proba(X_test)[:, 1]
        
        # Calcular ROC
        fpr_train, tpr_train, _ = roc_curve(y_train, y_score_train)
        roc_auc_train = auc(fpr_train, tpr_train)
        fpr_test, tpr_test, _ = roc_curve(y_test, y_score_test)
        roc_auc_test = auc(fpr_test, tpr_test)
        
        # Gráfico ROC
        fig_roc, ax_roc = plt.subplots(figsize=(8, 6))
        ax_roc.plot(fpr_train, tpr_train, color='blue', lw=2, label=f'Entrenamiento (AUC = {roc_auc_train:.2f})')
        ax_roc.plot(fpr_test, tpr_test, color='green', lw=2, label=f'Validación (AUC = {roc_auc_test:.2f})')
        ax_roc.plot([0, 1], [0, 1], color='red', lw=2, linestyle='--')
        ax_roc.set_xlim([0.0, 1.0])
        ax_roc.set_ylim([0.0, 1.05])
        ax_roc.set_xlabel('Tasa de Falsos Positivos (FPR)')
        ax_roc.set_ylabel('Tasa de Verdaderos Positivos (TPR)')
        ax_roc.set_title('Curva Característica de Operación del Receptor (ROC)')
        ax_roc.legend(loc="lower right")
        st.pyplot(fig_roc)
